# You should create a production build beforehand
#
# For example:
# yarn install
# yarn run build
#
FROM nginx:stable-alpine
COPY ./build /usr/share/nginx/html
RUN sed -i 's/index  index.html index.htm;/try_files \$uri \/index.html;/' /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]