name: Production build

on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - 
        name: Install dependencies
        run: yarn install    
      - 
        name: Generate build
        run: yarn run build
        env:
          CI: false
      - 
        name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: asic-agent-frontend-build
          path: |
            build
            Dockerfile.prod

  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: asic-agent-frontend-build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./asic-agent-frontend-build/
          file: ./asic-agent-frontend-build/Dockerfile.prod
          push: true
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asic-agent-frontend:production
            ${{ secrets.DOCKER_USERNAME }}/asic-agent-frontend:${{ github.event.release.tag_name }}
